# GitLab CI File
stages:
  - test
  - build
  - release

include:
  - component: $CI_SERVER_HOST/$CI_PROJECT_PATH/kaniko-build@$CI_COMMIT_SHA
    inputs:
      context: $CI_PROJECT_DIR/tests
      dockerfile: $CI_PROJECT_DIR/tests/Dockerfile
  - component: $CI_SERVER_HOST/$CI_PROJECT_PATH/buildah-build@$CI_COMMIT_SHA
    inputs:
      context: $CI_PROJECT_DIR/tests
      dockerfile: $CI_PROJECT_DIR/tests/Dockerfile
  - component: $CI_SERVER_HOST/$CI_PROJECT_PATH/pre-commit@$CI_COMMIT_SHA
    inputs:
      autofix: true
      access_token: $PRE_COMMIT_ACCESS_TOKEN

# The above is all you need. But for testing the pipelines are run for amd64 and arm64.
# So we override the jobs to use a matrix build. Again not needed by default.
# Currently there is no small arm runner

pre-commit:
  tags: [$RUNNER]
  parallel:
    matrix:
      - RUNNER: saas-linux-small-amd64
      - RUNNER: saas-linux-medium-arm64

buildah-build:
  tags: [$RUNNER]
  # Multiple pushes may cause race condition. Retry twice
  retry: 2
  parallel:
    matrix:
      - RUNNER: saas-linux-small-amd64
      - RUNNER: saas-linux-medium-arm64

kaniko-build:
  tags: [$RUNNER]
  # Multiple pushes may cause race condition. Retry twice
  retry: 2
  parallel:
    matrix:
      - RUNNER: saas-linux-small-amd64
      - RUNNER: saas-linux-medium-arm64

# If we are tagging a release with a specific convention ("v" + number) and all
# previous checks succeeded, we proceed with creating a release automatically.
create-release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG =~ /\d+/
  script: echo "Creating release $CI_COMMIT_TAG"
  release:
    tag_name: $CI_COMMIT_TAG
    description: "Release $CI_COMMIT_TAG of components repository $CI_PROJECT_PATH"
